"""
Override according to attribute values in your database.
TODO: Implement a good way to override these constants (e.g.: with a config file).
"""

'''
Special names.
'''
QUOTES = 'PRICE'  # Name (in the database) of the component representing the quotes of an instrument.

'''
Database attribute keys
'''
TYPE = 'TYPE'
BOND_TYPE = 'SUBTYPE'
QUOTE_TYPE = 'QUOTE_TYPE'
CURRENCY = 'CURRENCY'
YIELD_QUOTE_COMPOUNDING = 'YIELD_QUOTE_COMPOUNDING'
COMPOUNDING = 'COMPOUNDING'
YIELD_QUOTE_FREQUENCY = 'YIELD_QUOTE_FREQUENCY'
FREQUENCY = 'FREQUENCY'
ISSUE_DATE = 'ISSUE_DATE'
FIRST_ACCRUAL_DATE = 'FIRST_ACCRUAL_DATE'
MATURITY_DATE = 'MATURITY'
TENOR_PERIOD = 'FREQUENCY'
COUPON_FREQUENCY = 'FREQUENCY'
CALENDAR = 'CALENDAR'
BUSINESS_CONVENTION = 'BUSINESS_CONVENTION'
DATE_GENERATION = 'DATE_GENERATION'
SETTLEMENT_DAYS = 'SETTLEMENT_DAYS'
FACE_AMOUNT = 'FACE_AMOUNT'
COUPONS = 'COUPON'
DAY_COUNTER = 'DAY_COUNT'
REDEMPTION = 'REDEMPTION'
INDEX = 'INDEX'
SPREAD = 'SPREAD'
MULTIPLY_QUOTES_BY = 'MULTIPLY_QUOTES_BY'
BASE_CURRENCY = 'BASE_CURRENCY'
COUNTER_CURRENCY = 'COUNTER_CURRENCY'
BASE_RATE_DAY_COUNTER = 'BASE_RATE_DAY_COUNTER'
BASE_RATE_COMPOUNDING = 'BASE_RATE_COMPOUNDING'
BASE_RATE_FREQUENCY = 'BASE_RATE_FREQUENCY'
COUNTER_RATE_DAY_COUNTER = 'COUNTER_RATE_DAY_COUNTER'
COUNTER_RATE_COMPOUNDING = 'COUNTER_RATE_COMPOUNDING'
COUNTER_RATE_FREQUENCY = 'COUNTER_RATE_FREQUENCY'
PAYMENT_LAG = 'PAYMENT_LAG'

'''
Database attribute values
'''
BOND = 'BOND'
FIXEDRATE = 'FIXEDRATEBOND'
CALLABLEFIXEDRATE = 'CALLABLEFIXEDRATE'
FLOATINGRATE = 'FLOATINGRATE'
DISCOUNT = 'DISCOUNT'
CLEAN_PRICE = 'CLEAN_PRICE'
DIRTY_PRICE = 'DIRTY_PRICE'
YIELD = 'YIELD'
DEPOSIT_RATE = 'DEPOSIT_RATE'
DEPOSIT_RATE_FUTURE = 'DEPOSIT_RATE_FUTURE'
CURRENCY_FUTURE = 'CURRENCY_FUTURE'
SWAP_RATE = 'SWAP_RATE'
OIS_RATE = 'OIS'

'''
Configuration for yield curve classes
'''
# Names of attributes representing issue dates of securities in increasing order of precedence.
ISSUE_DATE_ATTRIBUTES = ['EFFECTIVE_PRECEDENCE_ISSUE', 'ISSUE']
